version: "3.8"

services:
  client:
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: ./client/Dockerfile

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
