server:
  ssl:
    enabled: true
    client-auth: need
    key-alias: server

    key-store: classpath:ssl/server.jks
    key-store-password: server
    key-store-type: JKS
    key-store-provider: SUN

    trust-store: classpath:ssl/server.jks
    trust-store-password: server
    trust-store-type: JKS
    trust-store-provider: SUN
