server:
  ssl:
    enabled: false

    key-store: classpath:ssl/client.jks
    key-store-password: client
    key-store-type: JKS
    key-store-provider: SUN

    trust-store: classpath:ssl/client.jks
    trust-store-password: client
    trust-store-type: JKS
    trust-store-provider: SUN

url:
  server: https://server:8080
